package Client


object Response {

  trait DataSetModelBase {

    def PageSize: Int

    def PageNr: Int

    def TotalCount: Int

    def Count: Int

    def Payload: Seq[PublicDatasetPayload]

    def Success: String

    def Error: String
  }

  case class PublicDataset(override val PageSize: Int,
                           override val PageNr: Int,
                           override val TotalCount: Int,
                           override val Count: Int,
                           override val Payload: Seq[PublicDatasetPayload],
                           override val Success: String,
                           override val Error: String) extends DataSetModelBase

  case class PublicDatasetPayload(LoanId: String,
                                  LoanNumber: Int,
                                  ListedOnUTC: String,
                                  BiddingStartedOn: String,
                                  BidsPortfolioManager: Double,
                                  BidsApi: Double,
                                  BidsManual: Double,
                                  UserName: String,
                                  NewCreditCustomer: String,
                                  LoanApplicationStartedDate: String,
                                  LoanDate: String,
                                  ContractEndDate: String,
                                  FirstPaymentDate: String,
                                  MaturityDate_Original: String,
                                  MaturityDate_Last: String,
                                  ApplicationSignedHour: Int,
                                  ApplicationSignedWeekday: Int,
                                  VerificationType: Int,
                                  LanguageCode: Int,
                                  Age: Int,
                                  DateOfBirth: String,
                                  Gender: Int,
                                  Country: String,
                                  County: String,
                                  City: String,
                                  AppliedAmount: Double,
                                  Amount: Double,
                                  Interest: Double,
                                  LoanDuration: Int,
                                  MonthlyPayment: Int,
                                  UseOfLoan: Int,
                                  Education: Int,
                                  MaritalStatus: Int,
                                  NrOfDependants: Int,
                                  EmploymentStatus: Int,
                                  EmploymentDurationCurrentEmployer: String,
                                  EmploymentPosition: String,
                                  WorkExperience: String,
                                  OccupationArea: Int,
                                  HomeOwnershipType: Int,
                                  IncomeFromPrincipalEmployer: Double,
                                  IncomeFromPension: Double,
                                  IncomeFromFamilyAllowance: Double,
                                  IncomeFromSocialWelfare: Double,
                                  IncomeFromLeavePay: Double,
                                  IncomeFromChildSupport: Double,
                                  IncomeOther: Double,
                                  IncomeTotal: Double,
                                  ExistingLiabilities: Int,
                                  RefinanceLiabilities: Int,
                                  LiabilitiesTotal: Double,
                                  DebtToIncome: Double,
                                  FreeCash: Double,
                                  MonthlyPaymentDay: Int,
                                  ActiveScheduleFirstPaymentReached: String,
                                  PlannedPrincipalTillDate: Int,
                                  PlannedInterestTillDate: Int,
                                  LastPaymentOn: String,
                                  CurrentDebtDaysPrimary: Int,
                                  DebtOccuredOn: String,
                                  CurrentDebtDaysSecondary: Int,
                                  DebtOccuredOnForSecondary: String,
                                  ExpectedLoss: Double,
                                  LossGivenDefault: Double,
                                  ExpectedReturn: Double,
                                  ProbabilityOfDefault: Double,
                                  DefaultDate: String,
                                  PrincipalOverdueBySchedule: Double,
                                  PlannedPrincipalPostDefault: Double,
                                  PlannedInterestPostDefault: Double,
                                  EAD1: Double,
                                  EAD2: Double,
                                  PrincipalRecovery: Double,
                                  InterestRecovery: Double,
                                  RecoveryStage: Int,
                                  StageActiveSince: String,
                                  ModelVersion: Int,
                                  Rating: String,
                                  EL_V0: String,
                                  Rating_V0: String,
                                  EL_V1: String,
                                  Rating_V1: String,
                                  EL_V2: Double,
                                  Rating_V2: String,
                                  LoanCancelled: String,
                                  Status: String,
                                  Restructured: String,
                                  ActiveLateCategory: String,
                                  WorseLateCategory: String,
                                  CreditScoreEsMicroL: String,
                                  CreditScoreEsEquifaxRisk: String,
                                  CreditScoreFiAsiakasTietoRiskGrade: String,
                                  CreditScoreEeMini: Double,
                                  PrincipalPaymentsMade: Double,
                                  InterestAndPenaltyPaymentsMade: Double,
                                  PrincipalWriteOffs: Double,
                                  InterestAndPenaltyWriteOffs: Double,
                                  PrincipalDebtServicingCost: Double,
                                  InterestAndPenaltyDebtServicingCost: Double,
                                  PrincipalBalance: Double,
                                  InterestAndPenaltyBalance: Double,
                                  NoOfPreviousLoansBeforeLoan: Int,
                                  AmountOfPreviousLoansBeforeLoan: Double,
                                  PreviousRepaymentsBeforeLoan: Double,
                                  PreviousEarlyRepaymentsBeforeLoan: Double,
                                  PreviousEarlyRepaymentsCountBeforeLoan: Int,
                                  GracePeriodStart: String,
                                  GracePeriodEnd: String,
                                  NextPaymentDate: String,
                                  NextPaymentNr: Int,
                                  NrOfScheduledPayments: Int,
                                  ReScheduledOn: String)

}
